<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f78a540e-be03-43b5-a7ab-9d7af64cb799</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Basket\Models\ShoppingCart.cs" Link="Models\ShoppingCart.cs" />
    <Compile Include="..\Basket\Models\ShoppingCartItem.cs" Link="Models\ShoppingCartItem.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Stripe.net" Version="47.4.0" />
    <PackageReference Include="QuestPDF" Version="2024.10.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
