<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.5.3" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>e75a5779-1e13-440d-abe5-c82f601c2792</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Basket\Basket.csproj" />
    <ProjectReference Include="..\Catalog\Catalog.csproj" />
    <ProjectReference Include="..\Identity\Identity.csproj" />
    <ProjectReference Include="..\Orders\Orders.csproj" />
    <ProjectReference Include="..\WebApp\WebApp.csproj" />
    <ProjectReference Include="..\Bff\Bff.csproj" />
    <ProjectReference Include="..\Notification\Notification.csproj" />
  </ItemGroup>

</Project>
