<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Catalog\Models\Product.cs" Link="Models\Product.cs" />
    <Compile Include="..\Basket\Models\ShoppingCart.cs" Link="Models\ShoppingCart.cs" />
    <Compile Include="..\Basket\Models\ShoppingCartItem.cs" Link="Models\ShoppingCartItem.cs" />
    <Compile Include="..\Orders\Models\Order.cs" Link="Models\Order.cs" />
    <Compile Include="..\Orders\Models\OrderItem.cs" Link="Models\OrderItem.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" Version="13.5.3" />
  </ItemGroup>

</Project>
